# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\projectt1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(522, 693)
        MainWindow.setMaximumSize(QtCore.QSize(522, 693))
        MainWindow.setStyleSheet("border: none;\n"
"background-color: #313131;")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNoEditMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #313131;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(24, 31, 24, 24)
        self.verticalLayout_2.setSpacing(24)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.displayLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLabel.sizePolicy().hasHeightForWidth())
        self.displayLabel.setSizePolicy(sizePolicy)
        self.displayLabel.setStyleSheet("font: 20px \"Roboto Mono\";\n"
"color: white;\n"
"font")
        self.displayLabel.setObjectName("displayLabel")
        self.verticalLayout_2.addWidget(self.displayLabel)
        self.dispayBox = QtWidgets.QTextEdit(self.frame_2)
        self.dispayBox.setEnabled(False)
        self.dispayBox.setStyleSheet("QTextEdit{border: 1px;\n"
"    font: 20pt \"Roboto Mono\";\n"
"border-radius: 14px;\n"
"background-color: #474747;\n"
"padding: 5px;\n"
"padding-left: 20px;\n"
"padding-top:15px;\n"
"font-size: 18px;\n"
"color: white;\n"
"}\n"
"\n"
"QTextEdit : placeholder{\n"
"    color: #707070;\n"
"}\n"
"")
        self.dispayBox.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.dispayBox.setReadOnly(True)
        self.dispayBox.setObjectName("dispayBox")
        self.verticalLayout_2.addWidget(self.dispayBox)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(24, 25, 24, 24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.previewLabel = QtWidgets.QLabel(self.frame_3)
        self.previewLabel.setStyleSheet("font: 20px \"Roboto Mono\";\n"
"color: white;\n"
"font")
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout.addWidget(self.previewLabel)
        self.previewBox = QtWidgets.QTextEdit(self.frame_3)
        self.previewBox.setEnabled(False)
        self.previewBox.setStyleSheet("QTextEdit{border: 1px;\n"
"    font: 20pt \"Roboto Mono\";\n"
"border-radius: 14px;\n"
"background-color: #474747;\n"
"padding: 5px;\n"
"padding-left: 20px;\n"
"padding-top:15px;\n"
"font-size: 18px;\n"
"color: white;\n"
"}\n"
"\n"
"QTextEdit : placeholder{\n"
"    color: #707070;\n"
"}\n"
"")
        self.previewBox.setReadOnly(True)
        self.previewBox.setObjectName("previewBox")
        self.verticalLayout.addWidget(self.previewBox)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 51, 0, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enqueueButton = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enqueueButton.setFont(font)
        self.enqueueButton.setStyleSheet("QPushButton {\n"
"    font: 100 8pt \"Roboto Mono\";\n"
"border: 1px;\n"
"    font: 20pt \"Roboto Mono\";\n"
"border-radius: 14px;\n"
"background-color: #4E5BB2;\n"
"padding: 10px;\n"
"padding-left: 20px;\n"
"font-size: 18px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: white;\n"
"color: #4E5BB2;\n"
"}")
        self.enqueueButton.setObjectName("enqueueButton")
        self.horizontalLayout.addWidget(self.enqueueButton)
        self.dequeButton = QtWidgets.QPushButton(self.frame_4)
        self.dequeButton.setStyleSheet("QPushButton {\n"
"border: 1px;\n"
"    font: 20pt \"Roboto Mono\";\n"
"border-radius: 14px;\n"
"background-color: #4E5BB2;\n"
"padding: 10px;\n"
"padding-left: 20px;\n"
"font-size: 18px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: white;\n"
"color: #4E5BB2;\n"
"}")
        self.dequeButton.setObjectName("dequeButton")
        self.horizontalLayout.addWidget(self.dequeButton)
        self.printButton = QtWidgets.QPushButton(self.frame_4)
        self.printButton.setStyleSheet("QPushButton {\n"
"border: 1px;\n"
"    font: 20pt \"Roboto Mono\";\n"
"border-radius: 14px;\n"
"    background-color: rgb(240, 189, 5);\n"
"padding: 10px;\n"
"padding-left: 20px;\n"
"font-size: 18px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: white;\n"
"color: #4E5BB2;\n"
"}")
        self.printButton.setObjectName("printButton")
        self.horizontalLayout.addWidget(self.printButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(24, 28, 24, 24)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputBox = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputBox.sizePolicy().hasHeightForWidth())
        self.inputBox.setSizePolicy(sizePolicy)
        self.inputBox.setMinimumSize(QtCore.QSize(0, 54))
        self.inputBox.setMaximumSize(QtCore.QSize(16777215, 53))
        self.inputBox.setStyleSheet("QLineEdit{border: 1px;\n"
"    font: 20px \"Roboto Mono\";\n"
"border-radius: 10px;\n"
"background-color: #474747;\n"
"padding: 5px;\n"
"padding-left: 20px;\n"
"font-size: 18px;\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit : placeholder{\n"
"    color: #707070;\n"
"font: 20px \"Roboto Mono\";\n"
"}\n"
"")
        self.inputBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.inputBox.setText("")
        self.inputBox.setObjectName("inputBox")
        self.horizontalLayout_2.addWidget(self.inputBox)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.displayLabel.setText(_translate("MainWindow", "Display"))
        self.dispayBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.previewLabel.setText(_translate("MainWindow", "Preview"))
        self.enqueueButton.setText(_translate("MainWindow", "Enqueue"))
        self.dequeButton.setText(_translate("MainWindow", "Dequeue"))
        self.printButton.setText(_translate("MainWindow", "Print"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Input"))
